services:
  postgres:
    image: postgres
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: mydb
    ports:
      - "5432:5432"

  mongo:
    image: mongo
    command: ["--bind_ip_all", "--port", "27017"]
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: pass
    ports:
      - "27017:27017"

  MySql:
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: pass
    ports:
      - "3306:3306"